import type { TypographOptions } from '../packages/typograph/src/index';
export interface Fixture {
  name: string;
  input: string;
  expected: string;
  options?: TypographOptions;
}
export const corpus: Fixture[] = [
  { name: 'dialogue', input: '"Hello," she said.', expected: '“Hello,” she said.' },
  { name: 'contraction', input: "It's ready.", expected: 'It’s ready.' },
  { name: 'name', input: "O'Brien met D'Angelo.", expected: 'O’Brien met D’Angelo.' },
  { name: 'plural possessive', input: "The dogs' bowls.", expected: 'The dogs’ bowls.' },
  { name: 'singular possessive', input: "Caleb's book.", expected: 'Caleb’s book.' },
  { name: 's possessive', input: "James' book.", expected: 'James’ book.' },
  { name: 'leading year', input: "The '90s were loud.", expected: 'The ’90s were loud.' },
  { name: 'leading twas', input: "'Twas a quiet night.", expected: '’Twas a quiet night.' },
  { name: 'leading em', input: "Give 'em a chance.", expected: 'Give ’em a chance.' },
  { name: 'rock and roll', input: "Rock 'n' roll.", expected: 'Rock ’n’ roll.' },
  { name: 'trailing elision', input: "Just hangin' around.", expected: 'Just hangin’ around.' },
  { name: 'yall', input: "Y'all ready?", expected: 'Y’all ready?' },
  { name: 'nested dialogue', input: '"She said \'hello\'."', expected: '“She said ‘hello’.”' },
  { name: 'nested contraction', input: "\"It's a 'good' day.\"", expected: '“It’s a ‘good’ day.”' },
  { name: 'quoted plural', input: "The 'dogs' are here.", expected: 'The ‘dogs’ are here.' },
  { name: 'quoted year', input: "The label says '90'.", expected: 'The label says ‘90’.' },
  { name: 'quoted number', input: '"Model 3"', expected: '“Model 3”' },
  { name: 'quoted single number', input: '"6"', expected: '“6”' },
  { name: 'parentheses', input: '("hello")', expected: '(“hello”)' },
  { name: 'em dash opening', input: 'She said—"go."', expected: 'She said—“go.”' },
  { name: 'colon opening', input: 'She said: "Go."', expected: 'She said: “Go.”' },
  { name: 'unicode contraction', input: "Élodie's café.", expected: 'Élodie’s café.' },
  { name: 'combining accent', input: "Café's menu.", expected: 'Café’s menu.' },
  { name: 'unicode letter', input: "𐐀's letter", expected: '𐐀’s letter' },
  { name: 'mixed Unicode opening', input: '“Hello"', expected: '“Hello”' },
  { name: 'already typographic', input: '“That’s ‘lovely’.”', expected: '“That’s ‘lovely’.”' },
  { name: 'empty double quote', input: '""', expected: '“”' },
  { name: 'empty single quote', input: "''", expected: '‘’' },
  { name: 'unclosed quote', input: '"Hello', expected: '“Hello' },
  { name: 'unsettled quote', input: '"', expected: '"' },
  {
    name: 'isolated measurement ambiguity',
    input: '6"',
    expected: '6"',
    options: { primes: true },
  },
  { name: 'unmatched closing', input: 'hello"', expected: 'hello"' },
  { name: 'derivative', input: "f'(x)", expected: "f'(x)", options: { primes: true } },
  {
    name: 'measurement preserves by default',
    input: 'She is 5\'10" tall.',
    expected: 'She is 5\'10" tall.',
  },
  {
    name: 'measurement compound',
    input: 'She is 5\'10" tall.',
    expected: 'She is 5′10″ tall.',
    options: { primes: true },
  },
  { name: 'measurement spaced', input: '5\' 10"', expected: '5′ 10″', options: { primes: true } },
  {
    name: 'measurement screen',
    input: 'The screen is 24" wide.',
    expected: 'The screen is 24″ wide.',
    options: { primes: true },
  },
  {
    name: 'measurement dimension label',
    input: 'Width: 24"',
    expected: 'Width: 24″',
    options: { primes: true },
  },
  {
    name: 'measurement feet',
    input: "A 6' board.",
    expected: 'A 6′ board.',
    options: { primes: true },
  },
  {
    name: 'measurements within dialogue',
    input: '"She is 5\'10\" tall."',
    expected: '“She is 5′10″ tall.”',
    options: { primes: true },
  },
  { name: 'coordinate', input: '40°42\'51"', expected: '40°42′51″', options: { primes: true } },
  {
    name: 'keep quoted number with primes',
    input: '"Model 3"',
    expected: '“Model 3”',
    options: { primes: true },
  },
  { name: 'ellipsis optional', input: 'Wait...', expected: 'Wait...' },
  {
    name: 'ellipsis enabled',
    input: 'Wait... really?',
    expected: 'Wait… really?',
    options: { ellipses: true },
  },
  { name: 'four dots', input: 'Wait....', expected: 'Wait....', options: { ellipses: true } },
  {
    name: 'numeric range unchanged',
    input: '1...5',
    expected: '1...5',
    options: { ellipses: true },
  },
  {
    name: 'dashes unchanged',
    input: 'one -- two --- three',
    expected: 'one -- two --- three',
    options: { ellipses: true },
  },
  { name: 'empty', input: '', expected: '' },
  { name: 'whitespace', input: ' \n\t\n ', expected: ' \n\t\n ' },
  {
    name: 'url apostrophe',
    input: "Visit https://example.com/it's-here",
    expected: "Visit https://example.com/it's-here",
  },
  {
    name: 'url ellipsis',
    input: 'https://example.com/a...b',
    expected: 'https://example.com/a...b',
    options: { ellipses: true },
  },
  { name: 'quoted url', input: '"https://example.com"', expected: '“https://example.com”' },
  { name: 'email', input: '"person@example.com"', expected: '“person@example.com”' },
  {
    name: 'quotes off',
    input: '"It\'s ready."',
    expected: '"It’s ready."',
    options: { quotes: false },
  },
  {
    name: 'apostrophes off',
    input: '"It\'s ready."',
    expected: "“It's ready.”",
    options: { apostrophes: false },
  },
  {
    name: 'all off',
    input: '"It\'s ready..."',
    expected: '"It\'s ready..."',
    options: { quotes: false, apostrophes: false },
  },
  { name: 'paragraphs', input: '"First.\n\n"Second."', expected: '“First.\n\n“Second.”' },
  {
    name: 'windows paragraphs',
    input: '"First.\r\n\r\n"Second."',
    expected: '“First.\r\n\r\n“Second.”',
  },
  { name: 'escaped quote', input: 'Say \\"hello\\".', expected: 'Say \\"hello\\".' },
  {
    name: 'preserved unicode',
    input: '‘’ “ ” ′ ″ ‴ «bonjour» „gut“',
    expected: '‘’ “ ” ′ ″ ‴ «bonjour» „gut“',
  },
];
