import { execFileSync } from 'node:child_process';
import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { principles } from '../packages/typograph/src/principles';

const root = process.cwd();
const downloadDir = resolve('apps/playground/public/downloads');
mkdirSync(downloadDir, { recursive: true });
const reference =
  '# Typography principles\n\nGenerated from `packages/typograph/src/principles.ts`. Change that source, then run `npm run build:resources`.\n\n' +
  principles
    .map(
      (p) =>
        `## ${p.title}\n\n${p.summary}\n\n**Category:** ${p.kind}\n\n**Intent:** ${p.intent}\n\n**When:** ${p.when}\n\n**Observe:** ${p.observe}\n\n**Action:** ${p.action}\n\n**Verify:** ${p.verify}\n\n**Exceptions:** ${p.exception}\n\n**Sources:** ${p.sources.map((s) => `[${s.title}](${s.url})`).join(' · ')}\n`,
    )
    .join('\n');
writeFileSync('skills/typograph/references/principles.md', reference);
cpSync('skills/typograph', 'apps/playground/public/skill', { recursive: true });
execFileSync(
  'tar',
  [
    '--exclude=._*',
    '--exclude=.DS_Store',
    '-czf',
    join(downloadDir, 'typograph-skill.tar.gz'),
    '-C',
    resolve('skills'),
    'typograph',
  ],
  { env: { ...process.env, COPYFILE_DISABLE: '1' } },
);
const [pack] = JSON.parse(
  execFileSync(
    'npm',
    [
      'pack',
      '--json',
      '--ignore-scripts',
      '--cache',
      '/tmp/typograph-pack-cache',
      '--pack-destination',
      downloadDir,
      '-w',
      '@calebduren/typograph',
    ],
    { cwd: root, encoding: 'utf8' },
  ),
);
writeFileSync(
  join(downloadDir, 'package.json'),
  JSON.stringify(
    { filename: pack.filename, integrity: pack.integrity, bytes: pack.size },
    null,
    2,
  ) + '\n',
);
const manifest = JSON.parse(readFileSync('packages/typograph/package.json', 'utf8'));
writeFileSync(
  'apps/playground/src/distribution.ts',
  `// Generated by build-resources.ts from the actual archive.\nexport const packageVersion = ${JSON.stringify(manifest.version)};\nexport const packageFilename = ${JSON.stringify(pack.filename)};\nexport const installCommand = ${JSON.stringify('npm install ./' + pack.filename)};\nexport const distributionLabel = 'Download the preview archive, then install it locally.';\n`,
);
console.log(`Built skill archive and ${pack.filename}.`);
