// Generated by build-resources.ts from the actual archive.
export const packageVersion = "2.0.0-next.1";
export const packageFilename = "calebduren-typograph-2.0.0-next.1.tgz";
export const installCommand = "npm install ./calebduren-typograph-2.0.0-next.1.tgz";
export const distributionLabel = 'Download the preview archive, then install it locally.';
